###  23.09.09
###  Darwin 24.3.0 Darwin Kernel Version 24.3.0: Thu Jan  2 20:24:23 PST 2025; root:xnu-11215.81.4~3/RELEASE_ARM64_T6020 MWVVRQX5VQGX arm64 root rl957 rl957
###  mac.arm64-64bit Tue Apr 15 15:13:39 2025

### [[[start of output from sessionInfo()]]] 
###    R version 4.3.0 (2023-04-21) 
###    Platform: aarch64-apple-darwin20 (64-bit) 
###    Running under: macOS 15.3.2 
###     
###    Matrix products: default 
###    BLAS:   /System/Library/Frameworks/Accelerate.framework/Versions/A/Frameworks/vecLib.framework/Versions/A/libBLAS.dylib  
###    LAPACK: /Library/Frameworks/R.framework/Versions/4.3-arm64/Resources/lib/libRlapack.dylib;  LAPACK version 3.11.0 
###     
###    locale: 
###    [1] en_US.UTF-8/en_US.UTF-8/en_US.UTF-8/C/en_US.UTF-8/en_US.UTF-8 
###     
###    time zone: America/New_York 
###    tzcode source: internal 
###     
###    attached base packages: 
###    [1] stats     graphics  grDevices utils     datasets  methods   base      
###     
###    other attached packages: 
###     [1] MASS_7.3-60      INLA_23.09.09    sp_2.1-3         spatialreg_1.2-9 Matrix_1.6-0     spdep_1.3-3      spData_2.3.0     
###     [8] patchwork_1.2.0  sf_1.0-16        lubridate_1.9.3  forcats_1.0.0    stringr_1.5.1    dplyr_1.1.4      purrr_1.0.2      
###    [15] readr_2.1.4      tidyr_1.3.1      tibble_3.2.1     ggplot2_3.5.1    tidyverse_2.0.0  
###     
###    loaded via a namespace (and not attached): 
###      [1] DBI_1.2.3             deldir_2.0-4          gridExtra_2.3         s2_1.1.6              sandwich_3.0-2        
###      [6] rlang_1.1.4           magrittr_2.0.3        multcomp_1.4-25       e1071_1.7-14          compiler_4.3.0        
###     [11] systemfonts_1.0.5     vctrs_0.6.5           pkgconfig_2.0.3       wk_0.9.1              crayon_1.5.2          
###     [16] fastmap_1.1.1         backports_1.5.0       magick_2.7.4          lemon_0.4.9           labeling_0.4.3        
###     [21] tzdb_0.4.0            graph_1.78.0          ragg_1.2.5            MatrixModels_0.5-2    bit_4.0.5             
###     [26] xfun_0.43             cachem_1.0.8          MoMAColors_0.0.0.9000 uuid_1.1-0            LearnBayes_2.15.1     
###     [31] broom_1.0.5           parallel_4.3.0        R6_2.5.1              stringi_1.8.4         RColorBrewer_1.1-3    
###     [36] car_3.1-2             boot_1.3-28.1         Rcpp_1.0.12           knitr_1.45            zoo_1.8-12            
###     [41] splines_4.3.0         timechange_0.3.0      tidyselect_1.2.1      rstudioapi_0.15.0     abind_1.4-5           
###     [46] codetools_0.2-19      lattice_0.22-5        plyr_1.8.9            withr_3.0.1           coda_0.19-4.1         
###     [51] survival_3.5-5        units_0.8-5           proxy_0.4-27          ggquiver_0.3.3        pillar_1.10.1         
###     [56] ggpubr_0.6.0          carData_3.0-5         tigris_2.2.0          KernSmooth_2.23-22    stats4_4.3.0          
###     [61] checkmate_2.3.2       generics_0.1.3        vroom_1.6.4           metR_0.14.0           hms_1.1.3             
###     [66] munsell_0.5.1         scales_1.3.0          class_7.3-22          glue_1.8.0            tools_4.3.0           
###     [71] data.table_1.16.0     biscale_1.0.0         ggsignif_0.6.4        mvtnorm_1.2-2         cowplot_1.1.1         
###     [76] grid_4.3.0            colorspace_2.1-1      areal_0.1.8.9000      nlme_3.1-162          cli_3.6.3             
###     [81] ggdark_0.2.1          rappdirs_0.3.3        textshaping_0.3.6     khroma_1.14.0         ggstream_0.1.0        
###     [86] expm_0.999-7          viridisLite_0.4.2     fmesher_0.1.1         Rgraphviz_2.44.0      gtable_0.3.5          
###     [91] R.methodsS3_1.8.2     rstatix_0.7.2         BiocGenerics_0.46.0   classInt_0.4-10       TH.data_1.1-2         
###     [96] farver_2.1.2          memoise_2.0.1         lifecycle_1.0.4       httr_1.4.7            bit64_4.0.5           
### [[[end of output from sessionInfo()]]]
 
inladatadir = /Users/rl957/Desktop/repos/Waves/waves/inla.model/data.files
inlaresdir = /Users/rl957/Desktop/repos/Waves/waves/inla.model/results.files
##inladatadir = data.files
##inlaresdir = results.files-%d

!INLA.libR! 
type = libR
R_HOME = /Library/Frameworks/R.framework/Resources

!INLA.Model! 
type = problem
dir = $inlaresdir
rinla.version =  23.09.09 
rinla.bdate =  Mon 16 Oct 20:16:52 +03 2023 (Version_23.09.09) 
return.marginals  = 1
return.marginals.predictor  = 0
hyperparameters  = 1
cpo  = 0
po  = 0
dic  = 0
mlik  = 1
q  = 0
graph  = 0
internal.opt  = 1
save.memory  = 0
config  = 0
likelihood.info  = 0
gcpo.enable  = 0
gcpo.verbose  = 0
gcpo.correct.hyperpar  = 1
gcpo.remove.fixed  = 1
gcpo.epsilon = 0.005 
gcpo.prior.diagonal = 1e-04 
gcpo.strategy = posterior 
gcpo.num.level.sets = -1 
gcpo.size.max = 32 
smtp =  default 
openmp.strategy =  default 
quantiles =  0.025 0.5 0.975 

!INLA.Data1!
type = data
likelihood =  poisson 
filename =  $inladatadir/file2b8aaa04c35 
weights =  $inladatadir/file2b8a21eb3106 
attributes =  $inladatadir/file2b8a16fead9b 
lpscale =  $inladatadir/file2b8a57df924f 
variant =  0 
quantile = -1
link.model =  log 
mix.use  = 0

!Predictor! 
type = predictor
dir = predictor
n =  544 
m =  0 
compute  = 1
offset =  $inladatadir/file2b8a2a37a6e8 
initial = 13.81551
fixed = 1
hyperid = 53001
prior = loggamma
parameters = 1 1e-05
to.theta = function (x) <<NEWLINE>>log(x)
from.theta = function (x) <<NEWLINE>>exp(x)

!(Intercept)!
dir =  fixed.effect00000001 
type = linear
covariates =  $inladatadir/file2b8a2baedeff 
compute = 1
mean =  0 
precision =  0 

!region!
dir =  random.effect00000001 
type = ffield
model =  bym2 
covariates =  $inladatadir/file2b8a2e593066 
diagonal = 1e-04 
constraint  = 0
extraconstraint = $inladatadir/file2b8a6178904f 
scale.model =  1 
adjust.for.con.comp =  1 
initial0 = 4
fixed0 = 0
hyperid0 = 11001
prior0 = pcprec
parameters0 = 1 0.01
to.theta0 = function (x) <<NEWLINE>>log(x)
from.theta0 = function (x) <<NEWLINE>>exp(x)
initial1 = -3
fixed1 = 0
hyperid1 = 11002
prior1 = table: $inladatadir/file2b8a105d547b
parameters1 = 
to.theta1 = function (x) <<NEWLINE>>log(x/(1 - x))
from.theta1 = function (x) <<NEWLINE>>exp(x)/(1 + exp(x))
n =  544 
nrep =  1 
graph =  $inladatadir/file2b8a5df973ec 
locations =  $inladatadir/file2b8a65b24dc0 
rankdef =  1 
compute = 1
vb.correct =  -1 

!INLA.Parameters! 
type = inla
int.strategy =  auto 
strategy =  auto 
adaptive.max =  25 
fast  = 1
h =  0.005 
dz =  0.75 
interpolator =  auto 
diff.log.dens =  6 
fp.hyperparam = $inlaresdir/joint.dat
tolerance.f =  0.002 
tolerance.g =  0.005 
tolerance.x =  0.001 
tolerance.step =  0.001 
hessian.force.diagonal  = 0
skip.configurations  = 1
adjust.weights  = 1
lincomb.derived.correlation.matrix  = 0
restart =  0 
optimiser =  default 
reordering =  -1 
n.points =  9 
cutoff =  1e-04 
step.len =  0 
stencil =  5 
diagonal =  0 
numint.maxfeval =  100000 
numint.relerr =  1e-05 
numint.abserr =  1e-06 
cmin =  -Inf 
b.strategy =  1 
nr.step.factor =  -0.1 
global.node.factor =  2 
global.node.degree =  2147483647 
stupid.search  = 1
stupid.search.max.iter =  1000 
stupid.search.factor =  1.05 
control.vb.enable  = 1
control.vb.verbose  = 1
control.vb.strategy =  mean 
control.vb.hessian.update =  2 
control.vb.hessian.strategy =  full 
control.vb.f.enable.limit.mean =  30 
control.vb.f.enable.limit.variance =  25 
control.vb.iter.max =  25 
control.vb.emergency =  25 
num.gradient =  central 
num.hessian =  central 
optimise.strategy =  smart 
use.directions  = 1
constr.marginal.diagonal =  1.490116e-08 
improved.simplified.laplace  = 0
parallel.linesearch  = 0
compute.initial.values  = 1
hessian.correct.skewness.only  = 1

!INLA.Expert! 
type = expert
disable.gaussian.check  = 0
dot.product.gain  = 0

!INLA.lp.scale! 
type = lp.scale


!INLA.pardiso!
type = pardiso
verbose =  0 
debug =  0 
parallel.reordering =  1 
nrhs =  -1 

