'Wave project: interpolate hex observations from county-level Covidestim data

Usage:
  hex-interpolate.R --save-observations <path> [--save-excluded <path>] --hex-mapping <path> --observations <path> [--geojson <path>] [--save-geojson <path>] [--exclude-threshold <pct>] [--debug-missingness]
  hex-interpolate.R (-h | --help)
  hex-interpolate.R --version

Options:
  --save-observations <path>  Where to save a CSV of observations for each hex [date, hexid, cases, infections, infectionsPC, Rt]
  --save-excluded <path>      Where to save a CSV detailing hexes and counties which were excluded [value, type]
  --save-geojson <path>       Where to save a GeoJSON of polygons for all hexes that participate in the model
  --hex-mapping <path>        Path to the CSV containing the FIPS/hex mapping [fips, hexid, proportion_from_fips, proportion_of_fips]
  --observations <path>       Path to CSV containing Covidestim output (as generated by `pullInputData.R`)
  --geojson <path>            Path to GeoJSON of hex polygons. Required for --save-geojson
  --exclude-threshold <pct>   Exclude hexes where > <pct>% of population has no data [default: 10]
  --debug-missingness         Print a list of hexes which are missing data pre-exclude
  -h --help  Show this screen.
  --version  Show version.

' -> doc

### Load in the necessary libraries 
### These are for the command line operation
library(docopt)
library(cli)

### These are for the execution of the R code 
suppressPackageStartupMessages( library(tidyverse) )
suppressPackageStartupMessages( library(sf) )
suppressPackageStartupMessages( library(geojsonio) )

args <- docopt(doc, version = 'hex-interpolate.R 0.1')
args$exclude_threshold <- as.numeric(args$exclude_threshold) # Passed as string

ps <- cli_process_start
pd <- cli_process_done

### Read in the details of the hexgrid 
### Each hex is represented by an ID number. 
### Each row represents a single hex and FIPs pair as well as the proportion
### of that hex that the listed FIPS contributes (proportion from FIPs) and
### the proportion (based on population) of the FIPs that the hex contains. 
### These proportions are used as weights for allocating infections to hexes.

ps("Reading {.file {args$hex_mapping}}")
mapping <- read_csv(
  args$hex_mapping,
  # "data-products/geo-hexes/hexid-fips-map.csv", ### for debugging 
  col_types = cols(
    hexid                = col_character(),
    fips                 = col_character(),
    proportion_from_fips = col_number(),
    proportion_of_fips   = col_number(),
  )
)
pd()

### Read in the covidestim generated data for each FIP 

ps("Reading {.file {args$observations}}")
observations <- read_csv(
  args$observations,
  # "data-products/covidestim-observations.csv",
  col_types = cols(
    fips         = col_character(),
    date         = col_date(),
    cases        = col_number(),
    Rt           = col_number(),
    infections   = col_number(),
    infectionsPC = col_number()
  )
)
pd()

### Read in the hex geometry 
if (!is.null(args$geojson)) {
  ps("Reading {.file {args$geojson}}")
  geojson <- read_sf(args$geojson, quiet = T)
  # geojson <- read_sf("data-products/geo-hexes/hexes.geojson", quiet = T)
  pd()
}

### Calculate the number of starting hexes 
n_hexes_at_start <- length(unique(mapping$hexid))

### Gather the counties in covidestim and hexgrid
counties_present_in_covidestim <- unique(observations$fips)
counties_present_in_mapping    <- unique(mapping$fips)
### Gather the unique hexes in hexgrid
hexids_present                 <- unique(mapping$hexid)

### Gather the counties present both hexgrid and covidestim
counties_present <- union(
  counties_present_in_covidestim,
  counties_present_in_mapping
)

### Calculate the fraction of missing counties that will be omitted from analysis

local({
  counties_not_in_covidestim <- setdiff(
    counties_present_in_mapping,
    counties_present_in_covidestim
  )

  counties_not_in_mapping <- setdiff(
    counties_present_in_covidestim,
    counties_present_in_mapping
  )

  frac_unusable_counties <-
    (length(counties_not_in_covidestim) + length(counties_not_in_mapping)) /
      length(counties_present)

  frac_unusable_counties_pct <-
    scales::label_percent(accuracy = 0.1)(frac_unusable_counties)

  cli_alert_warning("{.emph {frac_unusable_counties_pct}} counties unusable:")
  cli_ul()
  cli_li("{.emph {length(counties_not_in_covidestim)}} counties are in hex-mapping but not in Covidestim data")
  cli_li("{.emph {length(counties_not_in_mapping)}} counties are in Covidestim data but not in hex-mapping")
  cli_end()
})


ps("Calculating per-hex data missingness weighted by population")
missingness_by_hex <- left_join(
  mapping,
  tibble(fips = counties_present_in_covidestim, present = T),
  by = 'fips'
) %>%
  replace_na(list(present = F)) %>% # Now we know which FIPS are missing data
  group_by(hexid) %>%
  summarize(
    # Are any of this hex's FIPS missing data?
    any_missing_fips = any(present == F), 

    # How many are missing?
    n_missing = sum(present == F),

    # What proportion of the hex's population has no Covidestim observations?
    proportion_of_hex_missing = sum(
      proportion_from_fips[which(present == F)]
    )
  )
pd()

# If --debug-missingness, print which hexes have missing data
if (args$debug_missingness) {
  cli_alert_info("Missingness by hex:")
  print(missingness_by_hex %>% filter(any_missing_fips), n = 1000)
}

ps("Filtering out hexes with greater than {.emph {args$exclude_threshold}%} population missing in Covidestim data")
approved_hexes <- filter(
  missingness_by_hex,
  proportion_of_hex_missing < I(args$exclude_threshold)/100
  # proportion_of_hex_missing < I(50)/100 ### for debugging
) %>% pull(hexid)
n_hexes_discarded <- nrow(missingness_by_hex) - length(approved_hexes)
pd()
cli_alert_warning("Discarded {.val {n_hexes_discarded}} / {.val {n_hexes_at_start}} hexes")

### Assign each row (and hex/FIPS pair) the total cases, Rt, and infections
### from covidestim observations for its associated associated county 

result_uninterpolated <- mapping %>% filter(hexid %in% approved_hexes) %>%
  inner_join(observations, by = 'fips')

ultimately_included_fips   <- unique(result_uninterpolated$fips)
ultimately_included_hexids <- unique(result_uninterpolated$hexid)

### This step is the critical step in which we distribute the infections 
### from covidestim county data to the hex geometry. Here we aggregate so
### hex has only one number per 
### Note because a hex can have be part of more than one county, the sum of infections
### of all hexes within a FIPS will not equal the number of infections for that FIPs. 
ps("Interpolating hex observations from Covidestim observations")
result <- result_uninterpolated %>%
  group_by(hexid, date) %>%
  summarize(
    cases        = sum(proportion_of_fips   * cases),
    infections   = sum(proportion_of_fips   * infections),
    infectionsPC = sum(proportion_from_fips * infectionsPC),
    Rt           = sum(proportion_from_fips * Rt),
    .groups = 'drop'
  )
pd()

cli_alert_info("Interpolated data: missingness report (all should be FALSE):")
print(
  result %>%
    summarize(
      across(
        all_of(c("cases", "infections", "infectionsPC", "Rt")),
        ~any(is.na(.))
      )
    )
)

ultimately_excluded_fips <-
  setdiff(counties_present, ultimately_included_fips)
ultimately_excluded_hexids <-
  setdiff(hexids_present, ultimately_included_hexids)

### Create a GeoJSON which saves only those hexes which will not be used 
### in the analysis

if (!is.null(args$save_excluded)) {
  ps("Saving excluded fips+hexids report to {.file {args$save_excluded}}")
  write_csv(
    tibble(
      geography = c(ultimately_excluded_hexids, ultimately_excluded_fips),
      type = c(
        rep("hexid", length(ultimately_excluded_hexids)),
        rep("fips",  length(ultimately_excluded_fips))
      )
    ),
    args$save_excluded
  )
  pd()
}

### Create a GeoJSON which saves only those hexes which will be used 
### in the analysis
if (!is.null(args$geojson) && !is.null(args$save_geojson)) {
  ps("Saving GeoJSON of participating hexes to {.file {args$save_geojson}}")
  geojson_write(
    geojson %>% filter(hexid %in% ultimately_included_hexids),
    geometry  = "polygon",
    file      = args$save_geojson,
    overwrite = T,
  )
  pd()
}
### Create a CSV which holds the infections distributed across hexes 
ps("Saving interpolated observations to {.file {args$save_observations}}" )
write_csv(result, args$save_observations)
pd()
